# Generated by Django 4.0.6 on 2022-07-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api_app', '0009_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
