# Generated by Django 4.0.6 on 2022-07-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api_app', '0012_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
