# Generated by Django 4.0.6 on 2022-07-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api_app', '0014_quiz_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam_api_app.quiz')),
            ],
        ),
    ]
