# Generated by Django 4.0.6 on 2022-07-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api_app', '0015_solutions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solutions',
            new_name='submit_your_answers_here',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
    ]
