# Generated by Django 4.0.6 on 2022-07-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api_app', '0016_rename_solutions_submit_your_answers_here_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutions', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_api_app.quiz')),
                ('solutions_given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_api_app.teacher')),
            ],
        ),
    ]
