# Generated by Django 4.0.6 on 2022-07-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_api_app', '0020_alter_quiz_quiz_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit_your_answers_here',
            name='submitted_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
